apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: peer0.org3
  name: peer0.org3
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: peer0.org3
    spec:
      containers:
      - name: peer0-org3
        image: fiscoorg/front:bsn-0.2.0-gm
        ports:
        - containerPort: 8545
        - containerPort: 20200
        - containerPort: 30300
        - containerPort: 5002
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: peer0-org3-conf
        - mountPath: /dist/log
          name: peer0-org3-frontlog
        - mountPath: /dist/conf/application.yml
          name: peer0-org3-appconf
        workingDir: /data
      restartPolicy: Always
      volumes:
      - name: peer0-org3-conf
        hostPath:
          path: /root/nodes/fisco-2/node0
      - name: peer0-org3-frontlog
        hostPath:
          path: /root/nodes/fisco-2/frontlog
      - name: peer0-org3-appconf
        hostPath:
          path: /root/nodes/application.yml
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: peer0.org3
  name: peer0-org3
spec:
  clusterIP: 172.18.255.21
  ports:
  - name: rpc
    port: 8545
    targetPort: 8545
  - name: channel
    port: 20200
    targetPort: 20200
  - name: p2p
    port: 30300
    targetPort: 30300
  - name: front
    port: 5002
    targetPort: 5002
  selector:
    io.kompose.service: peer0.org3